apiVersion: v1
kind: Template
metadata:
  name: "apicast-tokenexchange-policy"
message: "APIcast Token Exchange Policy"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-policy

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-tokenexchange-policy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apicast-policy:token
    source:
      git:
        uri: https://github.com/pcastelo/apicast-tokenexchange-policy.git
        ref: 'master'
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'amp-apicast:${AMP_RELEASE}'

parameters:
- name: AMP_RELEASE
  required: true
  description: AMP Version (eg. 2.2.0-GA)
